package com.twitter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="TwitterStream") 
public class Tweet {
	private String tweetID;
	private String tweetUser;
	
	private String tweetText;
	private Double tweetLatitude;
	private Double tweetLongitude;
	
	private int[] countArray = null;
	
	@DynamoDBHashKey(attributeName = "Twitter_ID")
    @DynamoDBAutoGeneratedKey
	public String getTweetID() {
		return tweetID;
	}
	public void setTweetID(String tweetID) {
		this.tweetID = tweetID;
	}
	
	@DynamoDBAttribute(attributeName="Tweet_User")
	public String getTweetUser() {
		return tweetUser;
	}
	public void setTweetUser(String tweetUser) {
		this.tweetUser = tweetUser;
	}
	
	@DynamoDBAttribute(attributeName="Tweet_Text")
	public String getTweetText() {
		return tweetText;
	}
	public void setTweetText(String tweetText) {
		this.tweetText = tweetText;
	}
	
	@DynamoDBAttribute(attributeName="Tweet_Latitude")
	public Double getTweetLatitude() {
		return tweetLatitude;
	}
	public void setTweetLatitude(Double tweetLatitude) {
		this.tweetLatitude = tweetLatitude;
	}
	
	@DynamoDBAttribute(attributeName="Tweet_Longitude")
	public Double getTweetLongitude() {
		return tweetLongitude;
	}
	public void setTweetLongitude(Double tweetLongitude) {
		this.tweetLongitude = tweetLongitude;
	}
	public int[] getCountArray() {
		return countArray;
	}
	public void setCountArray(int[] countArray) {
		this.countArray = countArray;
	}
	

}
